name: baru
version: '0.1'
architectures: [all]
summary: Blue variant of the yaru theme.
description: |
  This is an unofficial blue variant of the Ubuntu Yaru theme.
grade: stable
confinement: strict

parts:
  theme:
    source: .
    plugin: meson
    build-packages: ["sassc", "libglib2.0-dev"]
    meson-parameters: ["--prefix=/"]
    override-build: |
      # First run normal build stage (the build stage of the meson plugin)
      snapcraftctl build
      # Link session file
      ln -s snap/session $SNAPCRAFT_PART_INSTALL/session
      # backward compability naming with symlinks and names
      ln -s Baru $SNAPCRAFT_PART_INSTALL/share/icons/Suru
      # remove unused artefacts in the snap (sessions and schemas)
      rm -rf $SNAPCRAFT_PART_INSTALL/share/*sessions $SNAPCRAFT_PART_INSTALL/share/glib-2.0
